language: python
python:
  - 3.5
  - 3.6
os:
  - linux
branches:
  only:
    - dev

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
        echo Installing Python virtualenv...;
        brew install python3;
        pip install --upgrade pip virtualenv;
        virtualenv -p python$PYTHON venv;
        source venv/bin/activate;
    fi

install:
  - |
    # do some pip setup
    pip install --upgrade pip
    pip install --upgrade pytest
    pip install --upgrade setuptools
    pip install --upgrade wheel
    # install from source dist
    python setup.py sdist
    pip install --verbose dist/*.tar.gz

script:
  - |
    pytest

jobs:
  include:
    # tests
    - stage: test
      os: linux
      python: 3.7
      dist: xenial
    - os: osx
      language: generic
      python: 3.5
      env: PYTHON=3.5
    - python: 3.6
      env: PYTHON=3.6
    - env: PYTHON=3.7

